#!/usr/bin/env python3

# do `modprobe sch_netem`
# before using

import argparse
import subprocess as sp

import enumerate_interfaces as ei
from query_yes_no import query_yes_no

def execute(cmd):
	print('-->', ' '.join(cmd))
	return sp.call(cmd, universal_newlines=True)

def show(args):
	show_cmd = ['sudo', 'tc', args.t, 'show']
	if args.i:
		show_cmd += ['dev', args.i]
	if args.s:
		show_cmd.insert(2, '-s')
	execute(show_cmd)

def flush(args):
	flush_cmd = ['sudo', 'tc', 'qdisc', 'del', 'dev', '', 'root']
	if args.a:
		if args.y or query_yes_no('Do you want flush all rules at all interfaces?', 'no'):
			for (interface, ip) in ei.all_interfaces():
				flush_cmd[-2] = interface
				execute(flush_cmd)
	else:
		flush_cmd[-2] = args.i
		execute(flush_cmd)

def loss(args):
	proto = {'udp': '17', 'tcp': '6'}
	prio_add_cmd = ['sudo', 'tc', 'qdisc', 'add', 'dev', args.interface, 'root', 'handle', '1:', 'prio']
	if execute(prio_add_cmd):
		return
	netem_add_cmd = ['sudo', 'tc', 'qdisc', 'add', 'dev', args.interface, 'parent', '1:1', 'handle', '10:', 
		'netem', 'loss', args.percent + '%']
	if execute(netem_add_cmd):
		return
	filter_add_cmd = ['sudo', 'tc', 'filter', 'add', 'dev', args.interface, 'parent', '1:0', 'u32',
		 'match', 'ip', 'protocol', proto[args.p], '0xff', 'classid', '1:1']
	execute(filter_add_cmd)

if __name__ == '__main__':
	cli_parser = argparse.ArgumentParser()
	cli_subparsers = cli_parser.add_subparsers()

	# Interface parser
	interface_parser = argparse.ArgumentParser(add_help=False)
	interface_parser.add_argument('interface', 
		help='interface {eth0, eth1, ppp0, ...}')

	# Show command
	parser_show = cli_subparsers.add_parser('show', 
		description='It shows rules for all interfaces by default.',
		help='show configuration of interface')
	parser_show.add_argument('-i', 
		help='interface {eth0, eth1, ppp0, ...}')
	parser_show.add_argument('-t', default='qdisc', choices=['qdisc', 'class', 'filter'],
		help='type {qdisc, class, filter}. qdisc by default')
	parser_show.add_argument('-s', action='store_true',
		help='statistics')
	parser_show.set_defaults(func=show)

	# Flush command
	parser_flush = cli_subparsers.add_parser('flush',
		description='It flushs all rules from one or all interfaces', 
		help='flush rules from interface')
	if_group = parser_flush.add_mutually_exclusive_group(required=True)
	if_group.add_argument('-i', 
		help='interface {eth0, eth1, ppp0, ...}')
	if_group.add_argument('-a', action='store_true',
		help='flush all rules from all interfaces')
	parser_flush.add_argument('-y', action='store_true',
		help='default yes action in the case of an argument -a')
	parser_flush.set_defaults(func=flush)

	# Loss command
	parser_loss = cli_subparsers.add_parser('loss', parents=[interface_parser], 
		description='It makes specified packet loss percent on network interface.',
		help='set the percentage of packet loss')
	parser_loss.add_argument('percent',
		help='percent of loss packets [0-100]%%')
	parser_loss.add_argument('-p', default='udp', choices=['tcp', 'udp'],
		help='protocol from /etc/protocols {tcp, udp}. udp by default')
	parser_loss.set_defaults(func=loss)

	args = cli_parser.parse_args()
	try:
		args.func(args)
	except AttributeError:
		cli_parser.parse_args(['-h'])